//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyCon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知剪影
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉
        ///嘎啦嘎啦
        ///飞腿郎
        ///快拳郎
        ///大舌头
        ///瓦斯弹
        ///双弹瓦斯
        ///独角犀牛
        ///钻角犀兽
        ///吉利蛋
        ///蔓藤怪
        ///袋兽
        ///墨海马
        ///海刺龙
        ///角金鱼
        ///金鱼王
        ///海星星
        ///宝石海星
        ///魔墙人偶
        ///飞天螳螂
        ///迷唇姐
        ///电击兽
        ///鸭嘴火兽
        ///凯罗斯
        ///肯 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_zh {
            get {
                return ResourceManager.GetString("text_Species_zh", resourceCulture);
            }
        }
    }
}
